// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01.CodeFirst;

namespace _01.CodeFirst.Migrations
{
    [DbContext(typeof(AwesomHotelDbContext))]
    partial class AwesomHotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_01.CodeFirst.Models.KeyCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardNumber");

                    b.HasKey("Id");

                    b.ToTable("KeyCards");
                });

            modelBuilder.Entity("_01.CodeFirst.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BedCount");

                    b.Property<decimal?>("Cost");

                    b.Property<bool>("IsAvailable");

                    b.Property<int>("Number");

                    b.Property<string>("RoomNickName")
                        .IsRequired();

                    b.Property<int>("RoomType");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("_01.CodeFirst.Models.RoomsKeyCards", b =>
                {
                    b.Property<int>("RoomId");

                    b.Property<int>("KeyCardId");

                    b.HasKey("RoomId", "KeyCardId");

                    b.HasIndex("KeyCardId");

                    b.ToTable("RoomsKeyCards");
                });

            modelBuilder.Entity("_01.CodeFirst.Models.RoomsKeyCards", b =>
                {
                    b.HasOne("_01.CodeFirst.Models.KeyCard", "KeyCard")
                        .WithMany("RoomsKeyCards")
                        .HasForeignKey("KeyCardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("_01.CodeFirst.Models.Room", "Room")
                        .WithMany("RoomsKeyCards")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
